### ISSUE TITLE
Python 3.3+ support

### ISSUE THREAD

**Issue by sabertiger** [tmm1/pygments.rb#152]
pygments.rb is currently using a development version of pygments 2.0.
Python3.3+ is already supported by the release version of pygments 2.0, which was released on Nov 9, 2014. Please pull latest released verison.

Current release from `vendor/pygments-main/CHANGES`

```
Version 2.0
-----------
(under development)

- Dropped Python 2.4 and 2.5 compatibility.  This is in favor of single-source
  compatibility between Python 2.6, 2.7 and 3.3+.
```

Current latest release version

```
Version 2.0.2
-------------
(released Jan 20, 2015)
```

.

**Comment by wigging** [comment]
Taken directly from http://pygments.org/faq/ for version 2.0.2:
![pygments](https://cloud.githubusercontent.com/assets/6828967/9648813/99cddd0e-51ba-11e5-92e2-42a73d43d108.png)
So please update `pygments.rb` to version 2.0.2.  Python 2 is now considered legacy code.

**Comment by aviaryan** [comment]
:+1:

**Comment by gengjiawen** [comment]
+1

**Comment by boutil** [comment]
Hi,
Debian is planning to remove python2, as it will very soon retire. Support for python3 is critical to allow the distribution of this project in Debian and its derivatives.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943257

thank you!

**Comment by terceiro** [comment]
I have a PR that works for me in #192 . is there anyone here that has access to a windows machine that could help debug the ci failure there?

**Comment by slonopotamus** [comment]
The failure has nothing  to do with GH_Actions, I also successfully reproduce it locally on Windows 10 + Ruby 2.7 + Python 3.8. I believe the problem is caused by newline character at the beginning of header received from `mentos.py`:

![image](https://user-images.githubusercontent.com/92637/91233145-467d7280-e739-11ea-83a8-7cb1e37265ee.png)

**Comment by slonopotamus** [comment]
UPDATE: Yes, my guess was correct. If I replace all `"\n"` with `" "` in `_write_error` and `_send_data` in `mentos.py`, it passes test initialization and half of tests.

So, the problem is: writing `\n` from Python side does *not* actually write `\n` but instead writes platform-dependent newline that becomes `\r\n` on Windows and breaks all byte counting.

I think you want to make sure that Python writes *bytes* to Ruby.

**Comment by ivanistheone** [comment]
@slonopotamus Good catch. Indeed there was some mix of unicode and bytes writing in the code:
I updated this PR https://github.com/tmm1/pygments.rb/pull/194 (specifically [this commit](https://github.com/tmm1/pygments.rb/pull/194/commits/0b6d0cc03fc9312995d72e85b5af38741f20105e) and windows tests pass now.

seems to be only some problem in ruby2.2 on mac
```/Users/runner/work/pygments.rb/pygments.rb/lib/pygments/popen.rb:163:in `lexers!': undefined method `inject' for nil:NilClass (NoMethodError) ```
