### ISSUE TITLE
Pygments 0.3.x broken on CentOS 5.8

### ISSUE THREAD

**Issue by bootstraponline** [tmm1/pygments.rb#43]
All tests are failing on [CentOS](https://www.centos.org/) 5.8. This issue impacts gollum. The old ffi pygments.rb worked correctly.

https://github.com/github/gollum/issues/550

**Comment by VoldemarLeGrand** [comment]
In my case the problem due to broken install of alternative Python 2.6 on RHEL 5: the installer created the executable `python` and `python2.6` but not `python2`. Latter still point to old system version 2.4. All 3 executables were declared in `$PATH`: 2.6 directory with `python` and `python2.6` first and then system directory `/usr/bin` with `python2`. So `python` command launch Python 2.6 while `python2` launch system Python 2.4.

But actually [`popen.rb`](https://github.com/tmm1/pygments.rb/blob/master/lib/pygments/popen.rb#L50) search for executable named `python2` to launch `mentos` process. So in my case the old version was used despite correct version of Python was in the `$PATH`.

Workaround is to create virtualenv directory with all 3 possible executables.

Hope this can help someone.
